import { ClerkProvider } from "@clerk/nextjs";
import React, { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}